version: '3.4'

services:
  rest:
    image: ${DOCKER_REGISTRY-}rest
    build:
      context: .
      dockerfile: REST/Dockerfile
    ports:
      - 24110:24110

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distcomp
    ports:
      - 5432:5432